{{--
    NBFIRA statutory footer — MUST appear on every page of every client-facing PDF
    and at the bottom of every client-facing email generated by Graphite/BizSure.
    Regulation: Authorised Financial Services Provider disclosure (NBFIRA Act).
    Implementation: single source of truth — update here and it propagates everywhere.
    Year rolls automatically on 1 January via date('Y').
--}}
<div class="nbfira-footer"
     style="width:100%; text-align:center; font-size:8pt; color:#555555;
            border-top:1px solid #cccccc; padding-top:4px; margin-top:12px;">
    Copyright {{ date('Y') }}. Alpha Direct Insurance Company (Pty) Ltd. All Rights Reserved.
    Alpha Direct Insurance Company (Proprietary) Limited is an Authorized Financial Services Provider
    | NBFIRA License No. 2/9/179
</div>
