<?php

return [
    'colors' => ['#109618','#dc3912','#ff9900','#753CEC','#3366cc','#D223A6','#B38686','#0A0A0B','#8E44AD', '#34495E', '#1D8348', '#D35400'],
    'policy_action' => [
        "allow_to_edit_on" => ['QUOTE','REJECTED'] // this will be use on policy action to check allow to edit or not
    ],
    'excel' => [
        'edit_policy' => [
            'coverage' => [
                   /* ================= PUBLIC LIABILITY ================= */
            'FIDELITYGUARANTEE' => [
                'headers' => [
                    'Risk Address',
                    'cover_type',
                    'cover_area',
                    'name_and_position',
                    'designation',
                    'length_of_service',
                    'amount_to_be_guaranteed',
                    'Premium',
                ],
                'default_value' => ['', '', '', '', ''],
                'column_widths' => [
                    'A' => 25,
                    'B' => 35,
                    'C' => 20,
                    'D' => 20,
                    'E' => 20,
                    'F' => 20,
                    'G' => 20,
                    'H' => 20,
                ],
                'field_mappings' => [
                    'coverage_detail' => [
                        'Risk Address' => 'riskAddress.address_name',
                        'cover_type' => 'cover_type',
                        'cover_area' => 'cover_area',
                        'name_and_position' => 'name_and_position',
                        'designation' => 'designation',
                        'length_of_service' => 'length_of_service',
                        'amount_to_be_guaranteed' => 'amount_to_be_guaranteed',
                        'Premium' => 'premium',
                    ],
                    'specified_items' => [],
                    'entities' => [],
                ],
            ],
            'COMMERCIALMOTOR' => [
                'headers' => [
                    'Risk Address',
                    'Registration No',
                    'Use',
                    'Type Of Cover',
                    'Coverage Value',
                    'Use Main',
                    'Type Of Cover Main',
                    'Calculated Value',
                    'Tracking Device',
                    'Security Features',
                    'Third Party Liability',
                    // Temporarily commented out fields
                    // 'Wreckage Removal',
                    // 'Window Glass',
                    // 'Locks Keys',
                    // 'Parts Accessories',
                    // 'Audio Accessories',
                    // 'Riot Strike',
                    // 'Car Hire Theft',
                    // 'Credit Shortfall',
                    // 'Insured Driver',
                    // 'Insured Family',
                    // 'Medical Expenses',
                    // 'Passenger Liability',
                    // 'Specified Accessories',
                    // 'Unorthorised Passanger Liability',
                    // 'Parking Facilities',
                    // 'Com Windscreen',
                    // 'Premium Wreckage Removal',
                    // 'Premium Window Glass',
                    // 'Premium Locks Keys',
                    // 'Premium Parts Accessories',
                    // 'Premium Audio Accessories',
                    // 'Premium Riot Strike',
                    // 'Premium Car Hire Theft',
                    // 'Premium Credit Shortfall',
                    // 'Premium Insured Driver',
                    // 'Premium Insured Family',
                    // 'Premium Medical Expenses',
                    // 'Premium Passenger Liability',
                    // 'Premium Third Party Liability',
                    // 'Premium Specified Accessories',
                    // 'Premium Unorthorised Passanger Liability',
                    // 'Premium Parking Facilities',
                    // 'Premium Com Windscreen',
                    // 'Own Damage',
                    // 'Own Damage Minimun Percent',
                    // 'Own Damage Minimum Amount',
                    // 'Windscreen',
                    // 'Windscreen Minimun Percent',
                    // 'Windscreen Minimum Amount',
                    // 'Loss Of Keys',
                    // 'Loss Of Keys Minimun Percent',
                    // 'Loss Of Keys Minimum Amount',
                ],
                'default_value' => array_fill(0, 11, ''),
                'column_widths' => [
                    'A' => 25, 'B' => 20, 'C' => 15, 'D' => 20, 'E' => 15, 'F' => 15, 'G' => 20,
                    'H' => 15, 'I' => 20, 'J' => 20, 'K' => 20,
                ],
                'style' => ['1'=>['font' => ['bold' => true]]],
                'field_mappings' => [
                    'motor' => [
                        'Risk Address' => 'riskAddress.address_name',
                        'Registration No' => 'registration_no',
                        'Use' => 'use',
                        'Type Of Cover' => 'type_of_cover',
                        'Coverage Value' => 'coverage_value',
                        'Use Main' => 'use_main',
                        'Type Of Cover Main' => 'type_of_cover_main',
                        'Calculated Value' => 'calculated_value',
                        'Tracking Device' => 'tracking_device',
                        'Security Features' => 'security_features',
                        'Third Party Liability' => 'third_party_liability',
                        // Temporarily commented out field mappings
                        // 'Wreckage Removal' => 'wreckage_removal',
                        // 'Window Glass' => 'window_glass',
                        // 'Locks Keys' => 'locks_keys',
                        // 'Parts Accessories' => 'parts_accessories',
                        // 'Audio Accessories' => 'audio_accessories',
                        // 'Riot Strike' => 'riot_strike',
                        // 'Car Hire Theft' => 'car_hire_theft',
                        // 'Credit Shortfall' => 'credit_shortfall',
                        // 'Insured Driver' => 'insured_driver',
                        // 'Insured Family' => 'insured_family',
                        // 'Medical Expenses' => 'medical_expenses',
                        // 'Passenger Liability' => 'passenger_liability',
                        // 'Specified Accessories' => 'specified_accessories',
                        // 'Unorthorised Passanger Liability' => 'unorthorised_passanger_liability',
                        // 'Parking Facilities' => 'parking_facilities',
                        // 'Com Windscreen' => 'com_windscreen',
                        // 'Premium Wreckage Removal' => 'premium_wreckage_removal',
                        // 'Premium Window Glass' => 'premium_window_glass',
                        // 'Premium Locks Keys' => 'premium_locks_keys',
                        // 'Premium Parts Accessories' => 'premium_parts_accessories',
                        // 'Premium Audio Accessories' => 'premium_audio_accessories',
                        // 'Premium Riot Strike' => 'premium_riot_strike',
                        // 'Premium Car Hire Theft' => 'premium_car_hire_theft',
                        // 'Premium Credit Shortfall' => 'premium_credit_shortfall',
                        // 'Premium Insured Driver' => 'premium_insured_driver',
                        // 'Premium Insured Family' => 'premium_insured_family',
                        // 'Premium Medical Expenses' => 'premium_medical_expenses',
                        // 'Premium Passenger Liability' => 'premium_passenger_liability',
                        // 'Premium Third Party Liability' => 'premium_third_party_liability',
                        // 'Premium Specified Accessories' => 'premium_specified_accessories',
                        // 'Premium Unorthorised Passanger Liability' => 'premium_unorthorised_passanger_liability',
                        // 'Premium Parking Facilities' => 'premium_parking_facilities',
                        // 'Premium Com Windscreen' => 'premium_com_windscreen',
                        // 'Own Damage' => 'own_damage',
                        // 'Own Damage Minimun Percent' => 'own_damage_minimun_percent',
                        // 'Own Damage Minimum Amount' => 'own_damage_minimum_amount',
                        // 'Windscreen' => 'windscreen',
                        // 'Windscreen Minimun Percent' => 'windscreen_minimun_percent',
                        // 'Windscreen Minimum Amount' => 'windscreen_minimum_amount',
                        // 'Loss Of Keys' => 'loss_of_keys',
                        // 'Loss Of Keys Minimun Percent' => 'loss_of_keys_minimun_percent',
                        // 'Loss Of Keys Minimum Amount' => 'loss_of_keys_minimum_amount',
                    ],
                    'coverage_detail' => [],
                    'specified_items' => [],
                    'entities' => [],
                ],
            ],
            'MOTORTRADERSEXTERNAL' => [
                'headers' => [
                    'Risk Address',
                    'Type Of Cover',
                    'Loss Or Damage Coverage Value',
                    'Loss Or Damage Calculated Value',
                    'Third Party Liability Coverage Value',
                    'Third Party Liability Calculated Value',
                    'Medical Benefits Coverage Value',
                    'Medical Benefits Calculated Value',
                    'Vehicle Lent Hire Coverage Value',
                    'Vehicle Lent Hire Calculated Value',
                    'Social Domestic Pleasure Coverage Value',
                    'Social Domestic Pleasure Calculated Value',
                    'Unauthoried Use Coverage Value',
                    'Unauthoried Use Calculated Value',
                    'Windscreen Coverage Value',
                    'Windscreen Calculated Value',
                    'Contigent Liability Coverage Value',
                    'Contigent Liability Calculated Value',
                    'Wreckage Removal Coverage Value',
                    'Wreckage Removal Calculated Value',
                    'Loss Of Key Coverage Value',
                    'Loss Of Key Calculated Value',
                    'Loss Of Use Of Customer Coverage Value',
                    'Loss Of Use Of Customer Calculated Value',
                    'Motor Cycle Motor Tricycle Coverage Value',
                    'Motor Cycle Motor Tricycle Calculated Value',
                    'Passanger Liability Respect Of Motor Coverage Value',
                    'Passanger Liability Respect Of Motor Calculated Value',
                    'Special Type Vehicle Coverage Value',
                    'Special Type Vehicle Calculated Value',
                    'Own Damage Minimun Percent',
                    'Own Damage Minimum Amount',
                    'Windscreen Minimun Percent',
                    'Windscreen Minimum Amount',
                ],
                'default_value' => array_fill(0, 34, ''),
                'column_widths' => [
                    'A' => 25, 'B' => 20, 'C' => 25, 'D' => 25, 'E' => 30, 'F' => 30, 'G' => 30, 'H' => 30,
                    'I' => 30, 'J' => 30, 'K' => 35, 'L' => 35, 'M' => 30, 'N' => 30, 'O' => 25, 'P' => 25,
                    'Q' => 30, 'R' => 30, 'S' => 30, 'T' => 30, 'U' => 30, 'V' => 30, 'W' => 40, 'X' => 40,
                    'Y' => 40, 'Z' => 40, 'AA' => 45, 'AB' => 45, 'AC' => 40, 'AD' => 40, 'AE' => 30, 'AF' => 30,
                    'AG' => 30, 'AH' => 30,
                ],
                'style' => ['1'=>['font' => ['bold' => true]]],
                'field_mappings' => [
                    'motor_traders' => [
                        'Risk Address' => 'riskAddress.address_name',
                        'Type Of Cover' => 'type_of_cover',
                        'Loss Or Damage Coverage Value' => 'loss_or_damage_coverage_value',
                        'Loss Or Damage Calculated Value' => 'loss_or_damage_calculated_value',
                        'Third Party Liability Coverage Value' => 'third_party_liability_coverage_value',
                        'Third Party Liability Calculated Value' => 'third_party_liability_calculated_value',
                        'Medical Benefits Coverage Value' => 'medical_benefits_coverage_value',
                        'Medical Benefits Calculated Value' => 'medical_benefits_calculated_value',
                        'Vehicle Lent Hire Coverage Value' => 'vehicle_lent_hire_coverage_value',
                        'Vehicle Lent Hire Calculated Value' => 'vehicle_lent_hire_calculated_value',
                        'Social Domestic Pleasure Coverage Value' => 'social_domestic_pleasure_coverage_value',
                        'Social Domestic Pleasure Calculated Value' => 'social_domestic_pleasure_calculated_value',
                        'Unauthoried Use Coverage Value' => 'unauthoried_use_coverage_value',
                        'Unauthoried Use Calculated Value' => 'unauthoried_use_calculated_value',
                        'Windscreen Coverage Value' => 'windscreen_coverage_value',
                        'Windscreen Calculated Value' => 'windscreen_calculated_value',
                        'Contigent Liability Coverage Value' => 'contigent_liability_coverage_value',
                        'Contigent Liability Calculated Value' => 'contigent_liability_calculated_value',
                        'Wreckage Removal Coverage Value' => 'wreckage_removal_coverage_value',
                        'Wreckage Removal Calculated Value' => 'wreckage_removal_calculated_value',
                        'Loss Of Key Coverage Value' => 'loss_of_key_coverage_value',
                        'Loss Of Key Calculated Value' => 'loss_of_key_calculated_value',
                        'Loss Of Use Of Customer Coverage Value' => 'Loss_of_use_of_customer_coverage_value',
                        'Loss Of Use Of Customer Calculated Value' => 'Loss_of_use_of_customer_calculated_value',
                        'Motor Cycle Motor Tricycle Coverage Value' => 'motor_cycle_motor_tricycle_coverage_value',
                        'Motor Cycle Motor Tricycle Calculated Value' => 'motor_cycle_motor_tricycle_calculated_value',
                        'Passanger Liability Respect Of Motor Coverage Value' => 'passanger_liability_respect_of_motor_coverage_value',
                        'Passanger Liability Respect Of Motor Calculated Value' => 'passanger_liability_respect_of_motor_calculated_value',
                        'Special Type Vehicle Coverage Value' => 'special_type_vehicle_coverage_value',
                        'Special Type Vehicle Calculated Value' => 'special_type_vehicle_calculated_value',
                        'Own Damage Minimun Percent' => 'own_damage_minimun_percent',
                        'Own Damage Minimum Amount' => 'own_damage_minimum_amount',
                        'Windscreen Minimun Percent' => 'windscreen_minimun_percent',
                        'Windscreen Minimum Amount' => 'windscreen_minimum_amount',
                    ],
                    'coverage_detail' => [],
                    'specified_items' => [],
                    'entities' => [],
                ],
            ],
            'MOTORTRADERSINTERNAL' => [
                'headers' => [
                    'Risk Address',
                    'Type Of Cover',
                    'Loss Or Damage Coverage Value',
                    'Loss Or Damage Calculated Value',
                    'Third Party Liability Coverage Value',
                    'Third Party Liability Calculated Value',
                    'Medical Benefits Coverage Value',
                    'Medical Benefits Calculated Value',
                    'Vehicle Lent Hire Coverage Value',
                    'Vehicle Lent Hire Calculated Value',
                    'Social Domestic Pleasure Coverage Value',
                    'Social Domestic Pleasure Calculated Value',
                    'Unauthoried Use Coverage Value',
                    'Unauthoried Use Calculated Value',
                    'Windscreen Coverage Value',
                    'Windscreen Calculated Value',
                    'Contigent Liability Coverage Value',
                    'Contigent Liability Calculated Value',
                    'Wreckage Removal Coverage Value',
                    'Wreckage Removal Calculated Value',
                    'Loss Of Key Coverage Value',
                    'Loss Of Key Calculated Value',
                    'Loss Of Use Of Customer Coverage Value',
                    'Loss Of Use Of Customer Calculated Value',
                    'Motor Cycle Motor Tricycle Coverage Value',
                    'Motor Cycle Motor Tricycle Calculated Value',
                    'Passanger Liability Respect Of Motor Coverage Value',
                    'Passanger Liability Respect Of Motor Calculated Value',
                    'Special Type Vehicle Coverage Value',
                    'Special Type Vehicle Calculated Value',
                    'Own Damage Minimun Percent',
                    'Own Damage Minimum Amount',
                    'Windscreen Minimun Percent',
                    'Windscreen Minimum Amount',
                ],
                'default_value' => array_fill(0, 34, ''),
                'column_widths' => [
                    'A' => 25, 'B' => 20, 'C' => 25, 'D' => 25, 'E' => 30, 'F' => 30, 'G' => 30, 'H' => 30,
                    'I' => 30, 'J' => 30, 'K' => 35, 'L' => 35, 'M' => 30, 'N' => 30, 'O' => 25, 'P' => 25,
                    'Q' => 30, 'R' => 30, 'S' => 30, 'T' => 30, 'U' => 30, 'V' => 30, 'W' => 40, 'X' => 40,
                    'Y' => 40, 'Z' => 40, 'AA' => 45, 'AB' => 45, 'AC' => 40, 'AD' => 40, 'AE' => 30, 'AF' => 30,
                    'AG' => 30, 'AH' => 30,
                ],
                'style' => ['1'=>['font' => ['bold' => true]]],
                'field_mappings' => [
                    'motor_traders_internal' => [
                        'Risk Address' => 'riskAddress.address_name',
                        'Type Of Cover' => 'type_of_cover',
                        'Loss Or Damage Coverage Value' => 'loss_or_damage_coverage_value',
                        'Loss Or Damage Calculated Value' => 'loss_or_damage_calculated_value',
                        'Third Party Liability Coverage Value' => 'third_party_liability_coverage_value',
                        'Third Party Liability Calculated Value' => 'third_party_liability_calculated_value',
                        'Medical Benefits Coverage Value' => 'medical_benefits_coverage_value',
                        'Medical Benefits Calculated Value' => 'medical_benefits_calculated_value',
                        'Vehicle Lent Hire Coverage Value' => 'vehicle_lent_hire_coverage_value',
                        'Vehicle Lent Hire Calculated Value' => 'vehicle_lent_hire_calculated_value',
                        'Social Domestic Pleasure Coverage Value' => 'social_domestic_pleasure_coverage_value',
                        'Social Domestic Pleasure Calculated Value' => 'social_domestic_pleasure_calculated_value',
                        'Unauthoried Use Coverage Value' => 'unauthoried_use_coverage_value',
                        'Unauthoried Use Calculated Value' => 'unauthoried_use_calculated_value',
                        'Windscreen Coverage Value' => 'windscreen_coverage_value',
                        'Windscreen Calculated Value' => 'windscreen_calculated_value',
                        'Contigent Liability Coverage Value' => 'contigent_liability_coverage_value',
                        'Contigent Liability Calculated Value' => 'contigent_liability_calculated_value',
                        'Wreckage Removal Coverage Value' => 'wreckage_removal_coverage_value',
                        'Wreckage Removal Calculated Value' => 'wreckage_removal_calculated_value',
                        'Loss Of Key Coverage Value' => 'loss_of_key_coverage_value',
                        'Loss Of Key Calculated Value' => 'loss_of_key_calculated_value',
                        'Loss Of Use Of Customer Coverage Value' => 'Loss_of_use_of_customer_coverage_value',
                        'Loss Of Use Of Customer Calculated Value' => 'Loss_of_use_of_customer_calculated_value',
                        'Motor Cycle Motor Tricycle Coverage Value' => 'motor_cycle_motor_tricycle_coverage_value',
                        'Motor Cycle Motor Tricycle Calculated Value' => 'motor_cycle_motor_tricycle_calculated_value',
                        'Passanger Liability Respect Of Motor Coverage Value' => 'passanger_liability_respect_of_motor_coverage_value',
                        'Passanger Liability Respect Of Motor Calculated Value' => 'passanger_liability_respect_of_motor_calculated_value',
                        'Special Type Vehicle Coverage Value' => 'special_type_vehicle_coverage_value',
                        'Special Type Vehicle Calculated Value' => 'special_type_vehicle_calculated_value',
                        'Own Damage Minimun Percent' => 'own_damage_minimun_percent',
                        'Own Damage Minimum Amount' => 'own_damage_minimum_amount',
                        'Windscreen Minimun Percent' => 'windscreen_minimun_percent',
                        'Windscreen Minimum Amount' => 'windscreen_minimum_amount',
                    ],
                    'coverage_detail' => [],
                    'specified_items' => [],
                    'entities' => [],
                ],
            ],
              'OTHER' => [
                'headers' => ['Risk Address','Vehicle','Member','Device','Sub Coverage','Limit','coverage string','ratefactor_type','ratefactor_value','ratefactor_AnnualWages','ratefactor_deposit_min_pre','discount_surcharge','discount_surcharge_type','discount_surcharge_value','premium'],
                'default_value' => ['','','','',' ','','','','','','','','','',''],
                'column_widths' =>['A' => 25,'B' => 25,'C' => 25,'D' => 25,'E' => 35,'F' => 15,'G' => 35,'H' => 15,'I' => 35,'J' => 35,'K' => 35,'L' => 35,'M' => 35,'N' => 35,'O' => 35],
                'style' => ['1'=>['font' => ['bold' => true]]],
                'field_mappings' => [
                    'coverage_detail' => [
                        'Risk Address' => 'riskAddress.address_name',
                        'Sub Coverage' => 'coverage.s_ScreenName',
                        'Limit' => 'coverage_value',
                        'coverage string' => 'coverage_value_string',
                        'ratefactor_type' => 'ratefactor_type',
                        'ratefactor_value' => 'ratefactor_value',
                        'ratefactor_AnnualWages' => 'ratefactor_AnnualWages',
                        'ratefactor_deposit_min_pre' => 'ratefactor_deposit_min_pre',
                        'discount_surcharge' => 'discount_surcharge',
                        'discount_surcharge_type' => 'discount_surcharge_type',
                        'discount_surcharge_value' => 'discount_surcharge_value',
                        'premium' => 'calculated_value',     
                    ],                 
                    'specified_items' => [   
                        'Risk Address' => 'riskAddress.address_name',
                    ],
                    'entities' => [
                        'Risk Address' =>    'riskAddress.address_name',
                        'Vehicle' => 'entity_type:Vehicle',
                        'Member' => 'entity_type:Member',
                        'Device' => 'entity_type:Device',
                    ],
                ],
            ]
              ],
        ],
    ],
    'date' => [
        'format' => 'd/m/Y',
        'js_format' => 'dd/mm/yyyy',
    ],
    'policy' => [
        'restrictionDate' => '2025-07-01'
    ],
];
