<?php

namespace AlphaDirect\Http\Controllers\Api\V1;

use AlphaDirect\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;

/**
 * Frontend → backend bridge for data-load failures.
 *
 * The V2 React frontend posts here when a fetch / React Query fails on
 * a page that should have rendered data. We email the developer team so
 * silent broken pages don't go undetected, AND we log to Laravel so the
 * report appears in cron / observability tooling.
 *
 * UAT 2026-05-26 brought up several pages that load forever without
 * surfacing the underlying error (Reconciliation, Audit Trail, Cron
 * Portal, etc.). Per Pramod's request, every such failure should email
 * developers@theriskco.com with a filterable tag so the team can spot
 * and triage, with a later move to a proper ticketing system.
 *
 * Throttled to 10/min per IP via the route registration. Authentication
 * is NOT required — we want errors from un-authed pages too — but the
 * payload is sanitised + truncated so we can't be abused to send
 * arbitrary email.
 */
class ErrorReportController extends Controller
{
    /** Mailbox the report lands at. Replaceable with ticketing later. */
    private const RECIPIENT = 'developers@theriskco.com';

    /** Subject tag so reports are filterable in Outlook / Gmail. */
    private const SUBJECT_TAG = '[GRAPHITE-V2-DATA-ERR]';

    public function store(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'route'       => 'nullable|string|max:500',
            'error'       => 'required|string|max:2000',
            'stack'       => 'nullable|string|max:8000',
            'context'     => 'nullable|string|max:200',
            'user_email'  => 'nullable|email|max:200',
            'browser'     => 'nullable|string|max:300',
            'occurred_at' => 'nullable|string|max:64',
        ]);

        $route   = $this->sanitise($validated['route']     ?? 'unknown');
        $errMsg  = $this->sanitise($validated['error']);
        $context = $this->sanitise($validated['context']   ?? '-');
        $user    = $this->sanitise($validated['user_email']?? '(unauthenticated)');
        $browser = $this->sanitise($validated['browser']   ?? '-');
        $occurAt = $this->sanitise($validated['occurred_at']?? now()->toIso8601String());
        $stack   = $this->sanitise($validated['stack']     ?? '', 8000);
        $ip      = $request->ip() ?? '-';

        $subject = sprintf(
            '%s %s — %s',
            self::SUBJECT_TAG,
            mb_substr($route, 0, 80),
            mb_substr(explode("\n", $errMsg)[0], 0, 120)
        );

        $body = <<<TEXT
Graphite V2 — Data Load Error Report
-------------------------------------

Route        : {$route}
Context      : {$context}
User         : {$user}
Browser      : {$browser}
Occurred at  : {$occurAt}
Client IP    : {$ip}

Error
-----
{$errMsg}

Stack (truncated)
-----------------
{$stack}

-------------------------------------
This email was generated by the V2 frontend data-load error reporter.
Filter on the "[GRAPHITE-V2-DATA-ERR]" subject tag to triage these in
your inbox. The intent is to migrate these to a proper ticketing
system once one is in place.
TEXT;

        // Mirror to Laravel log so cron / observability / log-stream
        // tooling has a record even when mail delivery is slow or fails.
        Log::warning('[ErrorReportController] data-load error', [
            'route' => $route,
            'error' => mb_substr($errMsg, 0, 500),
            'user'  => $user,
        ]);

        try {
            Mail::raw($body, function ($msg) use ($subject) {
                $msg->to(self::RECIPIENT)->subject($subject);
            });
        } catch (\Throwable $e) {
            // Email delivery failure must not break the caller. The log
            // line above already captured the underlying error report.
            Log::error('[ErrorReportController] mail send failed', [
                'error' => $e->getMessage(),
            ]);
        }

        // 204 No Content — caller is fire-and-forget; no body needed.
        return response()->json(null, 204);
    }

    /**
     * Trim, strip control characters, cap length. The frontend may
     * forward raw error messages including unprintable bytes — we don't
     * want those reaching Outlook.
     */
    private function sanitise(?string $value, int $maxLength = 2000): string
    {
        if ($value === null) {
            return '-';
        }
        $clean = preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F]/u', '', $value);
        $clean = trim((string) $clean);
        if ($clean === '') {
            return '-';
        }
        return mb_substr($clean, 0, $maxLength);
    }
}
