import { Link } from 'react-router-dom'
import { useReconciliationSummary } from '../../hooks/useReconciliation'
import { useCronReports } from '../../hooks/useCronReports'
import { getReportDownloadUrl } from '../../api/cronReports'
import LoadingSpinner from '../../components/common/LoadingSpinner'
import { fmtDateTime } from '../../utils/format'

// ── helpers ──────────────────────────────────────────────────────────────────
function fmtBytes(n: number | null): string {
  if (!n) return ''
  if (n < 1024) return `${n} B`
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(0)} KB`
  return `${(n / 1024 / 1024).toFixed(1)} MB`
}

const REPORT_COLORS: Record<string, { border: string; icon: string; badge: string }> = {
  blue:   { border: 'border-blue-200',   icon: 'bg-blue-100 text-blue-600',   badge: 'bg-blue-50 text-blue-700' },
  orange: { border: 'border-orange-200', icon: 'bg-orange-100 text-orange-600', badge: 'bg-orange-50 text-orange-700' },
  red:    { border: 'border-red-200',    icon: 'bg-red-100 text-red-600',    badge: 'bg-red-50 text-red-700' },
}

const STATUS_DOT: Record<string, string> = {
  ok:      'bg-green-500',
  error:   'bg-red-500',
  running: 'bg-blue-500 animate-pulse',
  never:   'bg-gray-300',
}

function ReportIcon({ icon }: { icon: string }) {
  if (icon === 'chart') return (
    <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
    </svg>
  )
  if (icon === 'clock') return (
    <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  )
  // alert
  return (
    <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.732-.833-2.464 0L4.35 16.5c-.77.833.192 2.5 1.732 2.5z" />
    </svg>
  )
}

// ── component ─────────────────────────────────────────────────────────────────
export default function ReconciliationDashboardPage() {
  const { data, isLoading }           = useReconciliationSummary()
  const { data: reports, isLoading: reportsLoading } = useCronReports()

  if (isLoading) {
    return (
      <div className="p-6 flex items-center justify-center min-h-[400px]">
        <LoadingSpinner size="lg" />
      </div>
    )
  }

  const allClear = data && data.totalOpen === 0

  const severityCards = [
    { label: 'Critical', count: data?.bySeverity.critical ?? 0, bg: 'bg-red-600',    text: 'text-white' },
    { label: 'High',     count: data?.bySeverity.high     ?? 0, bg: 'bg-orange-500', text: 'text-white' },
    { label: 'Medium',   count: data?.bySeverity.medium   ?? 0, bg: 'bg-yellow-400', text: 'text-yellow-900' },
    { label: 'Low',      count: data?.bySeverity.low      ?? 0, bg: 'bg-gray-300',   text: 'text-gray-700' },
  ]

  return (
    <div className="p-6 space-y-6">

      {/* ── Header ── */}
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-gray-800">Reconciliation Dashboard</h1>
        <Link
          to="/reconciliation/anomalies"
          className="px-4 py-2 bg-blue-600 text-white rounded-md text-sm font-medium hover:bg-blue-700 transition"
        >
          View All Anomalies
        </Link>
      </div>

      {/* ── Finance Reports Panel ── */}
      <div className="bg-white rounded-lg shadow-sm border">
        <div className="px-5 py-4 border-b flex items-center justify-between">
          <div>
            <h2 className="text-sm font-semibold text-gray-700">Finance Reports</h2>
            <p className="text-xs text-gray-400 mt-0.5">Generated by the Python cron engine · Excel format</p>
          </div>
        </div>
        <div className="divide-y divide-gray-100">
          {reportsLoading ? (
            <div className="px-5 py-8 flex justify-center">
              <LoadingSpinner size="sm" />
            </div>
          ) : !reports || reports.length === 0 ? (
            <div className="px-5 py-6 text-sm text-gray-400 text-center">No reports available yet. Run the cron engine to generate.</div>
          ) : (
            reports.map(report => {
              const colors = REPORT_COLORS[report.color] ?? REPORT_COLORS.blue
              return (
                <div key={report.job_key} className={`flex items-center gap-4 px-5 py-4 hover:bg-gray-50 transition border-l-4 ${colors.border}`}>
                  {/* Icon */}
                  <div className={`flex-shrink-0 w-10 h-10 rounded-lg flex items-center justify-center ${colors.icon}`}>
                    <ReportIcon icon={report.icon} />
                  </div>

                  {/* Info */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <span className="text-sm font-semibold text-gray-800">{report.label}</span>
                      {/* Status dot */}
                      <span className={`w-2 h-2 rounded-full flex-shrink-0 ${STATUS_DOT[report.status]}`} title={report.status} />
                      {report.elapsed && (
                        <span className="text-xs text-gray-400">ran in {report.elapsed}</span>
                      )}
                    </div>
                    <p className="text-xs text-gray-500 truncate mt-0.5">{report.description}</p>
                    <p className="text-xs text-gray-400 mt-1">
                      Last run: <span className="font-medium text-gray-600">{fmtDateTime(report.last_run_at, undefined, 'Never')}</span>
                      {report.file_size && <span className="ml-2 text-gray-400">· {fmtBytes(report.file_size)}</span>}
                    </p>
                  </div>

                  {/* Summary pill (context-aware) */}
                  <div className="hidden lg:flex flex-col items-end gap-1 text-right min-w-[120px]">
                    {report.job_key === 'written_premium' && report.summary?.gwp !== undefined && (
                      <span className={`text-xs px-2 py-1 rounded-full font-medium ${colors.badge}`}>
                        GWP P{Number(report.summary.gwp).toLocaleString('en', { maximumFractionDigits: 0 })}
                      </span>
                    )}
                    {report.job_key === 'ageing' && report.summary?.total_outstanding !== undefined && (
                      <span className={`text-xs px-2 py-1 rounded-full font-medium ${colors.badge}`}>
                        Outstanding P{Number(report.summary.total_outstanding).toLocaleString('en', { maximumFractionDigits: 0 })}
                      </span>
                    )}
                    {report.job_key === 'anomaly' && report.summary?.total_anomalies !== undefined && (
                      <span className={`text-xs px-2 py-1 rounded-full font-medium ${colors.badge}`}>
                        {Number(report.summary.total_anomalies)} anomalies
                      </span>
                    )}
                  </div>

                  {/* Download button */}
                  {report.has_file && report.filename ? (
                    <a
                      href={getReportDownloadUrl(report.filename)}
                      download={report.filename}
                      className="flex-shrink-0 flex items-center gap-1.5 px-3 py-2 bg-white border border-gray-200 rounded-md text-xs font-medium text-gray-700 hover:bg-gray-50 hover:border-gray-300 transition shadow-sm"
                      title={`Download ${report.label}`}
                    >
                      <svg className="w-3.5 h-3.5 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                      </svg>
                      Download
                    </a>
                  ) : (
                    <span className="flex-shrink-0 px-3 py-2 text-xs text-gray-300 border border-dashed border-gray-200 rounded-md cursor-not-allowed">
                      No file
                    </span>
                  )}
                </div>
              )
            })
          )}
        </div>
      </div>

      {/* ── All Clear Banner ── */}
      {allClear ? (
        <div className="bg-green-50 border border-green-200 rounded-lg px-6 py-5 flex items-center gap-4">
          <div className="flex-shrink-0 w-12 h-12 bg-green-100 rounded-full flex items-center justify-center">
            <svg className="w-7 h-7 text-green-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
          <div>
            <p className="text-green-800 font-semibold text-base">All Clear — No Open Anomalies</p>
            <p className="text-green-600 text-sm mt-0.5">
              All {data.totalResolved} previously detected issues have been resolved.
              {data.latestRun && ` Last reconciliation checked ${data.latestRun.policiesChecked?.toLocaleString()} policies.`}
            </p>
          </div>
          <div className="ml-auto">
            <Link
              to="/reconciliation/anomalies"
              className="text-xs text-green-700 underline underline-offset-2 hover:text-green-800"
            >
              View history
            </Link>
          </div>
        </div>
      ) : (
        <>
          {/* Severity Cards */}
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
            {severityCards.map(card => (
              <div key={card.label} className={`${card.bg} ${card.text} rounded-lg p-5 shadow-sm`}>
                <p className="text-sm font-medium opacity-90">{card.label}</p>
                <p className="text-3xl font-bold mt-1">{card.count}</p>
              </div>
            ))}
          </div>

          {/* Stats Row */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Open vs Resolved */}
            <div className="bg-white rounded-lg shadow-sm border p-5">
              <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">Overview</h2>
              <div className="flex items-center gap-8">
                <div>
                  <p className="text-3xl font-bold text-red-600">{data?.totalOpen ?? 0}</p>
                  <p className="text-sm text-gray-500">Open Anomalies</p>
                </div>
                <div>
                  <p className="text-3xl font-bold text-green-600">{data?.totalResolved ?? 0}</p>
                  <p className="text-sm text-gray-500">Resolved</p>
                </div>
              </div>
            </div>

            {/* Latest Run */}
            <div className="bg-white rounded-lg shadow-sm border p-5">
              <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">Latest Run</h2>
              {data?.latestRun ? (
                <div className="space-y-1 text-sm">
                  <div className="flex justify-between">
                    <span className="text-gray-500">Run #{data.latestRun.id}</span>
                    <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${
                      data.latestRun.status === 'completed' ? 'bg-green-100 text-green-700' :
                      data.latestRun.status === 'running'   ? 'bg-blue-100 text-blue-700' :
                      data.latestRun.status === 'failed'    ? 'bg-red-100 text-red-700' :
                      'bg-gray-100 text-gray-600'
                    }`}>
                      {data.latestRun.status}
                    </span>
                  </div>
                  <p className="text-gray-600">Type: <span className="font-medium">{data.latestRun.runType}</span></p>
                  <p className="text-gray-600">Policies checked: <span className="font-medium">{data.latestRun.policiesChecked}</span></p>
                  <p className="text-gray-600">Anomalies found: <span className="font-medium">{data.latestRun.anomaliesFound}</span></p>
                  <p className="text-gray-400 text-xs mt-1">
                    Started: {new Date(data.latestRun.startedAt).toLocaleString()}
                    {data.latestRun.completedAt && <> · Completed: {new Date(data.latestRun.completedAt).toLocaleString()}</>}
                  </p>
                </div>
              ) : (
                <p className="text-gray-400 text-sm">No runs recorded yet.</p>
              )}
            </div>
          </div>

          {/* Anomaly Type Breakdown */}
          <div className="bg-white rounded-lg shadow-sm border p-5">
            <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">Open Anomalies by Type</h2>
            {Object.keys(data?.byType ?? {}).length === 0 ? (
              <p className="text-gray-400 text-sm">No open anomalies.</p>
            ) : (
              <ul className="divide-y divide-gray-100">
                {Object.entries(data?.byType ?? {})
                  .sort(([, a], [, b]) => (b as number) - (a as number))
                  .map(([type, count]) => (
                    <li key={type} className="flex items-center justify-between py-2">
                      <Link
                        to={`/reconciliation/anomalies?anomaly_type=${type}`}
                        className="text-sm text-blue-600 hover:underline font-medium"
                      >
                        {type.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())}
                      </Link>
                      <span className="text-sm font-semibold text-gray-700">{count as number}</span>
                    </li>
                  ))}
              </ul>
            )}
          </div>
        </>
      )}
    </div>
  )
}
