<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $employer_group_name ?? 'Quote Report' }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 0;
            padding: 20px;
            color: #000;
        }
        .header {
            margin-bottom: 20px;
            border-bottom: 2px solid #000;
            padding-bottom: 15px;
        }
        .logo {
            font-size: 18px;
            font-weight: bold;
            color: #0066cc;
            margin-bottom: 5px;
        }
        .logo-sub {
            font-size: 12px;
            color: #000;
        }
        .report-title {
            text-align: center;
            font-size: 16px;
            font-weight: bold;
            margin: 15px 0;
        }
        .report-info {
            text-align: right;
            font-size: 10px;
            color: #666;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #000;
            padding: 6px 8px;
            text-align: left;
            font-size: 11px;
        }
        th {
            background-color: #f0f0f0;
            font-weight: bold;
            text-align: center;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .total-row {
            font-weight: bold;
            background-color: #e9e9e9;
        }
        .total-row td {
            border-top: 2px solid #000;
        }
        .total-amount {
            text-decoration: underline;
            text-decoration-style: double;
        }
        .comments {
            margin-top: 20px;
            font-size: 10px;
            color: #666;
        }
        .comments-label {
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo">
            <img alt="Logo" src="{{ public_path('images/logo.png') }}" style="max-height: 60px; max-width: 200px;" />
        </div>
        <div class="report-info">
            Generated by: {{ $user->firstName }} {{ $user->lastName }}<br>
            Generated on: {{ $generated_at }}
        </div>
    </div>

    <div class="report-title">{{ $employer_group_name }}</div>

    <table>
        <thead>
            <tr>
                <th>Principle FullNames</th>
                <th>Age Group</th>
                <th>Gender/Sex</th>
                <th>No of Dependents</th>
                <th>Health Insurance Plan</th>
                <th>Premium</th>
            </tr>
        </thead>
        <tbody>
            @foreach($policies as $policy)
            <tr>
                <td>{{ $policy->employee_name ?? 'N/A' }}</td>
                <td>{{ $policy->age_group ?? 'N/A' }}</td>
                <td>{{ $policy->gender ?? 'N/A' }}</td>
                <td>{{ $policy->total_beneficiaries ?? 0 }}</td>
                <td>{{ $policy->health_plan ?? 'Premier' }}</td>
                <td>P {{ number_format($policy->premium ?? 0, 2) }}</td>
            </tr>
            @endforeach
            <tr class="total-row">
                <td colspan="5"><strong>Total</strong></td>
                <td class="total-amount"><strong>P {{ number_format($total_premium, 2) }}</strong></td>
            </tr>
        </tbody>
    </table>

    <div class="comments">
        <span class="comments-label">Comments:</span> Actual pricing may vary once full demographic data is available.
    </div>
</body>
</html>

